meta_product_name: "Subdesk"
meta_title: "Trouvez votre parfait collocataire de travail"
meta_description: "Avec Subdesk trouvez votre parfait collocataire de travail"
meta_image: "cover.png" # should exist in `app/assets/images/`
